name: Comment on fork PRs

permissions:
  pull-requests: write
  repository-projects: write


on:
  workflow_call:

# Cancel any existing runs of this workflow on the same branch/pr
# We always want to build/deploy/test a new commit over an older one
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:

  comment:
    runs-on: mdb-dev
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      # - name: Find associated pull request
      #   id: pr
      #   uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
      #   with:
      #     script: |
      #       const response = await github.rest.search.issuesAndPullRequests({
      #         q: 'repo:${{ github.repository }} is:pr sha:${{ github.event.workflow_run.head_sha }}',
      #         per_page: 1,
      #       })
      #       const items = response.data.items
      #       if (items.length < 1) {
      #         console.error('No PRs found')
      #         return
      #       }
      #       const pullRequestNumber = items[0].number
      #       console.info("Pull request number is", pullRequestNumber)
      #       return pullRequestNumber
      # - uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.issues.createComment({
      #         issue_number: ${{ steps.pr.outputs.result }},
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: '${{ github.sha }}, ${{ github.repository }}'
      #       })
